[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
name = "mysql_common"
description = "MySql protocol primitives"
license = "MIT/Apache-2.0"
homepage = "https://github.com/blackbeam/rust_mysql_common"
documentation = "https://docs.rs/mysql_common"
repository = "https://github.com/blackbeam/rust_mysql_common"
keywords = ["mysql", "database"]
categories = ["database"]
version = "0.15.0"
edition = "2018"

[dependencies]
atoi = "0.3"
base64 = "0.10"
bitflags = "1"
bit-vec = "0.5"
byteorder = "1"
chrono = "0.4"
lazy_static = "1"
num-bigint = "0.2"
rand = "0.6"
regex = "1"
sha1 = "0.6"
sha2 = "0.8"
smallvec = "0.6"
time = "0.1"
twox-hash = "1"
uuid = "0.7"
serde = "1"
serde_json = "1"

[dependencies.rustc-serialize]
version = "0.3"
optional= true

[features]
default = []
rustc_serialize = ["rustc-serialize"]
